# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # 打印环境变量
    - name: Print environment variables
      run: |
        echo "REMOTE_HOST: ${{ secrets.REMOTE_HOST }}"
        echo "REMOTE_USER: ${{ secrets.REMOTE_USER }}"
        echo "SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}"

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Run a command remotely
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: sh /root/fish-server/scripts/deploy.sh
